package quic

//go:generate sh -c "./mockgen_private.sh quic mock_stream_internal_test.go github.com/wheelcomplex/qk streamI"
//go:generate sh -c "./mockgen_private.sh quic mock_receive_stream_internal_test.go github.com/wheelcomplex/qk receiveStreamI"
//go:generate sh -c "./mockgen_private.sh quic mock_send_stream_internal_test.go github.com/wheelcomplex/qk sendStreamI"
//go:generate sh -c "./mockgen_private.sh quic mock_stream_sender_test.go github.com/wheelcomplex/qk streamSender"
//go:generate sh -c "./mockgen_private.sh quic mock_stream_getter_test.go github.com/wheelcomplex/qk streamGetter"
//go:generate sh -c "./mockgen_private.sh quic mock_stream_frame_source_test.go github.com/wheelcomplex/qk streamFrameSource"
//go:generate sh -c "./mockgen_private.sh quic mock_crypto_stream_test.go github.com/wheelcomplex/qk cryptoStream"
//go:generate sh -c "./mockgen_private.sh quic mock_stream_manager_test.go github.com/wheelcomplex/qk streamManager"
//go:generate sh -c "./mockgen_private.sh quic mock_unpacker_test.go github.com/wheelcomplex/qk unpacker"
//go:generate sh -c "./mockgen_private.sh quic mock_quic_aead_test.go github.com/wheelcomplex/qk quicAEAD"
//go:generate sh -c "./mockgen_private.sh quic mock_gquic_aead_test.go github.com/wheelcomplex/qk gQUICAEAD"
//go:generate sh -c "./mockgen_private.sh quic mock_session_runner_test.go github.com/wheelcomplex/qk sessionRunner"
//go:generate sh -c "./mockgen_private.sh quic mock_quic_session_test.go github.com/wheelcomplex/qk quicSession"
//go:generate sh -c "./mockgen_private.sh quic mock_packet_handler_test.go github.com/wheelcomplex/qk packetHandler"
//go:generate sh -c "./mockgen_private.sh quic mock_unknown_packet_handler_test.go github.com/wheelcomplex/qk unknownPacketHandler"
//go:generate sh -c "./mockgen_private.sh quic mock_packet_handler_manager_test.go github.com/wheelcomplex/qk packetHandlerManager"
//go:generate sh -c "./mockgen_private.sh quic mock_multiplexer_test.go github.com/wheelcomplex/qk multiplexer"
